// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package interfaceInjection

// Injectors from wire.go:

func initializeBaz() (Bar, error) {
	myFooer := provideMyFooer()
	bar := provideBar(myFooer)
	return bar, nil
}
